object Table {
  deck : array
  state : string
  turnHolder : Player
  activePlayers : array
  dealerHand : array
  deck : array
}

object Player {
  id : string
  hand : array
  score : int
  bet : int
  balance : int
}
