package Server {
  class Table {
    state : string
    turnHolder : Player
    activePlayers : list<Player>
    dealerHand : list<int>
    deck : list<int>
  }

  class Player {
    id : string
    hand : list<int>
    bet : int
    balance : int
  }
}
