participant client as c
participant server as s

note right of c: Client Connects \nto the server
c -> s: onConnect()
s --> c: updateTable(table)

alt User Joins a table to play
c -> s: joinTable()
s -> s: addClient\nToConnected\nList()
s -> c: updateTable(table)

note right of c: player bet
c -> s: bet(amount: int)
alt bet already made
s --> c: errorAlreadyPlacedBet()
else bet > balance
s --> c: errorCantAffordBet()
else
s -> s: updatePot
end

note right of c: hit / stand logic
alt hit
c -> s: hit()
s -> s: PickRandomCard
note right of s: Checks if card \nfits game logic
else stand
c -> s: stand()
s -> s: skipClientTurn
end
s --> c: updateTable(table)

loop on changes to the table
s -> c: updateTable(table)
end

else User Joins a table ot spectate
c -> s: spectateTable()
s -> s: addClient\nToConnected\nList()

loop on changes to the table
s -> c: updateTable(table)
end
end
c -> s: leaveTable
s --> c: updateTable(table)
